FROM node:20-bookworm

WORKDIR /app

COPY package.json package-lock.json ./
COPY storybook-static ./storybook-static
RUN npm ci
RUN npx -y playwright@1.54.0 install --with-deps

ENTRYPOINT ["npx", "playwright"]